
--DROP TABLE Combustible
CREATE TABLE [dbo].[Combustible](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idTipo] [int] NOT NULL,
	[precio] [numeric](18, 4) NOT NULL,
	[idEmpresa] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
