USE [NexusDB]
GO

/****** Object:  Table [dbo].[facturas]    Script Date: 19/12/2025 17:06:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[facturas](
	[id_facturas] [int] IDENTITY(1,1) NOT NULL,
	[n_factura] [bigint] NOT NULL,
	[empresa_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_facturas] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[n_factura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[facturas]  WITH CHECK ADD FOREIGN KEY([empresa_id])
REFERENCES [dbo].[empresas] ([id])
GO


